example:
  config-bean:
    enabled: true # config bean takes precedence over mongock's spring boot spring boot config props.


mongock:
  enabled: true
  transaction-enabled: true
  migration-scan-package:
    - dev.nazeem.mongock.db

spring:
  data:
    mongodb:
      uri: mongodb://localhost/test?retryWrites=true